### ISSUE TITLE
Fix lag 0 truth

### ISSUE THREAD

**Issue by lepisma** [reichlab/flusight-csv-tools#9]
`getSeasonTruth` doesn't handle the edge and peak calculation correctly if asked for small lag values (< 4).

**Comment by nickreich** [comment]
Does this issue impact the file you created last week?

**Comment by lepisma** [comment]
No, thats fine. Adding more description in this issue.

**Comment by lepisma** [comment]
This is because there is no data for such lag values. If there is even a single week missing, we can't (theoretically) calculate targets like `peak` and `peak_wk`. Closing this as there is no workaround other than noticing the missing data and moving the lag value up a bit.
